[experiment_section]
#details
sample_random_nav_goal: False
sample_xlow: -0.5
sample_xhigh: 0
sample_ylow : 1.55
sample_yhigh: 1.7
default_goal: -0.4,1.66, 1.57 #TODO - use this
can_offset_x: 0
can_offset_y: 0
#note that can offsets changes the sample_xlow range accordingly
log_folder: /home/sritee/catkin_ws/src/navr/logs_test/
config_folder: /home/sritee/catkin_ws/src/navr/config/
#height above which can is considered lifted
success_height: 0.5 

[gazebo]
#gazebo params
render: True
sleep_time_after_fetchspawn: 6
#max duration experiment will run
experiment_duration: 60
gazebo_launch: /home/sritee/catkin_ws/src/navr/launch/gazebo_and_localization.launch
move_script: /home/sritee/catkin_ws/src/navr/launch/test.launch
world_file: /home/sritee/catkin_ws/src/navr/worlds/hard_world_2.world



