[experiment_section]
#details
sample_random_nav_goal: True
sample_xlow: -0.5
sample_xhigh: 0
sample_ylow : 1.55
sample_yhigh: 1.7
default_goal: -0.4,1.66, 1.57 #TODO - use this

[gazebo]
#gazebo params
render: False
sleep_time_after_fetchspawn: 10
experiment_duration: 60
gazebo_launch: /home/sritee/catkin_ws/src/navr/launch/gazebo_and_localization_norviz.launch
move_script: /home/sritee/catkin_ws/src/navr/launch/test.launch



